### ISSUE TITLE
Moving from blueimp/nightwatch to blueimp/wdio

### ISSUE THREAD

**Issue by ujwaldhakal** [blueimp/wdio#2]
Since your previous package has been archived now we i want to move on to this one so are there any docs available for this so ? Building all things which come from nightwatch to this wdio would cost us a big amount of time

**Comment by blueimp** [comment]
Hey @ujwaldhakal 
there is no pressing need for you to switch, unless you want the benefits of this new project.
All the commits of the old project are still available, e.g. the last commit before the deprecation notice and archival: https://github.com/blueimp/nightwatch/tree/8572509f6dbc7ae0cc378f490a60cfdb2c606313
If you wanna continue using the blueimp/nightwatch project, I recommend forking from this commit.
The [blueimp/nightwatch](https://hub.docker.com/r/blueimp/nightwatch) docker images are also still available on Docker Hub, they simply won't be updated anymore.

There is no specific documentation in this repository on how to move from NightwatchJS to WebdriverIO, as this has more to do with the frameworks themselves than with this Docker setup.
I highly recommend giving WebdriverIO a try though, as it has a great API and much better compatibility with the different Webdriver implementations.

Completely off-topic:
I read your Github profile description and had a good laugh, good sense of humour. 😆

**Comment by ujwaldhakal** [comment]
Thank you @blueimp  and i really appreciate your contribution on open source ! Thank you kudos !

**Comment by blueimp** [comment]
Hey @ujwaldhakal, do you think we can close this issue, or is there something left open that you would like to be clarified?

**Comment by ujwaldhakal** [comment]
Ok i am good with it
