### ISSUE TITLE
Question: Is there a way to run chrome test on host (local Mac) machine instead of linux container?

### ISSUE THREAD

**Issue by kumarpatel** [blueimp/wdio#5]
I've tried modifying ```  hostname: "chromedriver",``` in chrome.js
to ```hostname: "host.docker.internal",```

Thoughts?

**Comment by blueimp** [comment]
Hi @kumarpatel,
sure that is possible and changing the `hostname` property in [chrome.js](https://github.com/blueimp/wdio/blob/master/chrome.js#L2) to `host.docker.internal` is the first right step.
Additionally you will also have to change the `assetsDir` property in [chrome.js](https://github.com/blueimp/wdio/blob/master/chrome.js#L32) to `process.env.MACOS_ASSETS_DIR`, so tests which make use of the assets directory don't fail.

Your [chrome.js](https://github.com/blueimp/wdio/blob/master/chrome.js) config file will look like this (not showing the unchanged properties):

```js
exports.config = Object.assign({}, require('./hooks'), {
  hostname: 'host.docker.internal',
  // ...
  assetsDir: process.env.MACOS_ASSETS_DIR,
  // ...
})
```

Finally, you will have to [download chromedriver](http://chromedriver.chromium.org/downloads) and then start it with the following arguments:

```sh
./chromedriver --port=4444 --whitelisted-ips=
```

Make sure you download the correct `chromedriver` version matching the version of your Chrome installation.

Then you can run the containerized WebdriverIO against your local desktop chrome:

```sh
docker-compose run --rm wdio
```

Please note that I do not recommend doing this, as the whole point of this project is to dockerize dependencies as much as possible, so it's easy to run tests on build servers.

Any reason why you prefer to run against desktop chrome versus the dockerized Linux version?

**Comment by kumarpatel** [comment]
Awesome. Thanks. I shall give this is a try. mobile-chrome, mobile-safari, safari and chrome (on linux) are working extremely well.

Another question: android-emulator.sh script. 
Is the purpose of this script to run it on all avd's only once to upload android.host file?
or is it to run it every single time to start the emulators before mobile-chrome tests are executed?


> Any reason why you prefer to run against desktop chrome versus the dockerized Linux version?
My only reason to run it on Chrome for Mac is because I assume there are differences between Chrome for Mac vs Chrome for Linux vs Chrome for Windows. What do you think?

**Comment by blueimp** [comment]
In general I think Chrome for Linux is on par with the Mac and Windows versions in regards to Website testing - the JS engine and HTML parser are the same.
Also, many developers use Chrome for Mac as main testing device, so in my opinion there's no need to test Chrome for Mac/Windows specifically.

Technically you don't have to use the `android-emulator.sh` script to start the Android emulators every time, but you do have to supply the `-writable-system` argument (which is used by the script) every time, else the simulator will not use the overlay filesystem with the updated hostnames.
So in the end, I do recommend to use the script every time.

**Comment by kumarpatel** [comment]
You above worked. Thanks again.
